<?php
$lang[1]=array('iso' =>'aa','friendly'=>'Afar');
$lang[2]=array('iso' =>'ab','friendly'=>'Abkhazian');
$lang[3]=array('iso' =>'ae','friendly'=>'Avestan');
$lang[4]=array('iso' =>'af','friendly'=>'Afrikaans');
$lang[5]=array('iso' =>'ak','friendly'=>'Akan');
$lang[6]=array('iso' =>'am','friendly'=>'Amharic');
$lang[7]=array('iso' =>'an','friendly'=>'Aragonese');
$lang[8]=array('iso' =>'ar','friendly'=>'Arabic');
$lang[9]=array('iso' =>'as','friendly'=>'Assamese');
$lang[10]=array('iso' =>'av','friendly'=>'Avaric');
$lang[11]=array('iso' =>'ay','friendly'=>'Aymara');
$lang[12]=array('iso' =>'az','friendly'=>'Azerbaijani');
$lang[13]=array('iso' =>'ba','friendly'=>'Bashkir');
$lang[14]=array('iso' =>'be','friendly'=>'Belarusian');
$lang[15]=array('iso' =>'bg','friendly'=>'Bulgarian');
$lang[16]=array('iso' =>'bh','friendly'=>'Bihari');
$lang[17]=array('iso' =>'bi','friendly'=>'Bislama');
$lang[18]=array('iso' =>'bm','friendly'=>'Bambara');
$lang[19]=array('iso' =>'bn','friendly'=>'Bengali');
$lang[20]=array('iso' =>'bo','friendly'=>'Tibetan');
$lang[21]=array('iso' =>'bo','friendly'=>'Tibetan');
$lang[22]=array('iso' =>'br','friendly'=>'Breton');
$lang[23]=array('iso' =>'bs','friendly'=>'Bosnian');
$lang[24]=array('iso' =>'ca','friendly'=>'Catalan; Valencian');
$lang[25]=array('iso' =>'ce','friendly'=>'Chechen');
$lang[26]=array('iso' =>'ch','friendly'=>'Chamorro');
$lang[27]=array('iso' =>'co','friendly'=>'Corsican');
$lang[28]=array('iso' =>'cr','friendly'=>'Cree');
$lang[29]=array('iso' =>'cs','friendly'=>'Czech');
$lang[30]=array('iso' =>'cs','friendly'=>'Czech');
$lang[31]=array('iso' =>'cu','friendly'=>'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic');
$lang[32]=array('iso' =>'cv','friendly'=>'Chuvash');
$lang[33]=array('iso' =>'cy','friendly'=>'Welsh');
$lang[34]=array('iso' =>'cy','friendly'=>'Welsh');
$lang[35]=array('iso' =>'da','friendly'=>'Danish');
$lang[36]=array('iso' =>'de','friendly'=>'German');
$lang[37]=array('iso' =>'de','friendly'=>'German');
$lang[38]=array('iso' =>'dv','friendly'=>'Divehi; Dhivehi; Maldivian');
$lang[39]=array('iso' =>'dz','friendly'=>'Dzongkha');
$lang[40]=array('iso' =>'ee','friendly'=>'Ewe');
$lang[41]=array('iso' =>'el','friendly'=>'Greek, Modern (1453-)');
$lang[42]=array('iso' =>'el','friendly'=>'Greek, Modern (1453-)');
$lang[43]=array('iso' =>'en','friendly'=>'English');
$lang[44]=array('iso' =>'eo','friendly'=>'Esperanto');
$lang[45]=array('iso' =>'es','friendly'=>'Spanish; Castilian');
$lang[46]=array('iso' =>'et','friendly'=>'Estonian');
$lang[47]=array('iso' =>'eu','friendly'=>'Basque');
$lang[48]=array('iso' =>'fa','friendly'=>'Persian');
$lang[49]=array('iso' =>'ff','friendly'=>'Fulah');
$lang[50]=array('iso' =>'fi','friendly'=>'Finnish');
$lang[51]=array('iso' =>'fj','friendly'=>'Fijian');
$lang[52]=array('iso' =>'fo','friendly'=>'Faroese');
$lang[53]=array('iso' =>'fr','friendly'=>'French');
$lang[54]=array('iso' =>'fy','friendly'=>'Western Frisian');
$lang[55]=array('iso' =>'ga','friendly'=>'Irish');
$lang[56]=array('iso' =>'gd','friendly'=>'Gaelic; Scottish Gaelic');
$lang[57]=array('iso' =>'gl','friendly'=>'Galician');
$lang[58]=array('iso' =>'gn','friendly'=>'Guarani');
$lang[59]=array('iso' =>'gu','friendly'=>'Gujarati');
$lang[60]=array('iso' =>'gv','friendly'=>'Manx');
$lang[61]=array('iso' =>'ha','friendly'=>'Hausa');
$lang[62]=array('iso' =>'he','friendly'=>'Hebrew');
$lang[63]=array('iso' =>'hi','friendly'=>'Hindi');
$lang[64]=array('iso' =>'ho','friendly'=>'Hiri Motu');
$lang[65]=array('iso' =>'hr','friendly'=>'Croatian');
$lang[66]=array('iso' =>'ht','friendly'=>'Haitian; Haitian Creole');
$lang[67]=array('iso' =>'hu','friendly'=>'Hungarian');
$lang[68]=array('iso' =>'hy','friendly'=>'Armenian');
$lang[69]=array('iso' =>'hz','friendly'=>'Herero');
$lang[70]=array('iso' =>'ia','friendly'=>'Interlingua (International Auxiliary Language Association)');
$lang[71]=array('iso' =>'id','friendly'=>'Indonesian');
$lang[72]=array('iso' =>'ie','friendly'=>'Interlingue; Occidental');
$lang[73]=array('iso' =>'ig','friendly'=>'Igbo');
$lang[74]=array('iso' =>'ii','friendly'=>'Sichuan Yi; Nuosu');
$lang[75]=array('iso' =>'ik','friendly'=>'Inupiaq');
$lang[76]=array('iso' =>'io','friendly'=>'Ido');
$lang[77]=array('iso' =>'is','friendly'=>'Icelandic');
$lang[78]=array('iso' =>'is','friendly'=>'Icelandic');
$lang[79]=array('iso' =>'it','friendly'=>'Italian');
$lang[80]=array('iso' =>'iu','friendly'=>'Inuktitut');
$lang[81]=array('iso' =>'ja','friendly'=>'Japanese');
$lang[82]=array('iso' =>'jv','friendly'=>'Javanese');
$lang[83]=array('iso' =>'ka','friendly'=>'Georgian');
$lang[84]=array('iso' =>'kg','friendly'=>'Kongo');
$lang[85]=array('iso' =>'ki','friendly'=>'Kikuyu; Gikuyu');
$lang[86]=array('iso' =>'kk','friendly'=>'Kazakh');
$lang[87]=array('iso' =>'kl','friendly'=>'Kalaallisut; Greenlandic');
$lang[88]=array('iso' =>'km','friendly'=>'Central Khmer');
$lang[89]=array('iso' =>'kn','friendly'=>'Kannada');
$lang[90]=array('iso' =>'ko','friendly'=>'Korean');
$lang[91]=array('iso' =>'kr','friendly'=>'Kanuri');
$lang[92]=array('iso' =>'ks','friendly'=>'Kashmiri');
$lang[93]=array('iso' =>'ku','friendly'=>'Kurdish');
$lang[94]=array('iso' =>'kv','friendly'=>'Komi');
$lang[95]=array('iso' =>'kw','friendly'=>'Cornish');
$lang[96]=array('iso' =>'ky','friendly'=>'Kirghiz; Kyrgyz');
$lang[97]=array('iso' =>'la','friendly'=>'Latin');
$lang[98]=array('iso' =>'lb','friendly'=>'Luxembourgish; Letzeburgesch');
$lang[99]=array('iso' =>'lg','friendly'=>'Ganda');
$lang[100]=array('iso' =>'li','friendly'=>'Limburgan; Limburger; Limburgish');
$lang[101]=array('iso' =>'ln','friendly'=>'Lingala');
$lang[102]=array('iso' =>'lo','friendly'=>'Lao');
$lang[103]=array('iso' =>'lt','friendly'=>'Lithuanian');
$lang[104]=array('iso' =>'lu','friendly'=>'Luba-Katanga');
$lang[105]=array('iso' =>'lv','friendly'=>'Latvian');
$lang[106]=array('iso' =>'mg','friendly'=>'Malagasy');
$lang[107]=array('iso' =>'mh','friendly'=>'Marshallese');
$lang[108]=array('iso' =>'mi','friendly'=>'Maori');
$lang[109]=array('iso' =>'mk','friendly'=>'Macedonian');
$lang[110]=array('iso' =>'ml','friendly'=>'Malayalam');
$lang[111]=array('iso' =>'mn','friendly'=>'Mongolian');
$lang[112]=array('iso' =>'mr','friendly'=>'Marathi');
$lang[113]=array('iso' =>'ms','friendly'=>'Malay');
$lang[114]=array('iso' =>'mt','friendly'=>'Maltese');
$lang[115]=array('iso' =>'my','friendly'=>'Burmese');
$lang[116]=array('iso' =>'na','friendly'=>'Nauru');
$lang[117]=array('iso' =>'nb','friendly'=>'Bokmål, Norwegian; Norwegian Bokmål');
$lang[118]=array('iso' =>'nd','friendly'=>'Ndebele, North; North Ndebele');
$lang[119]=array('iso' =>'ne','friendly'=>'Nepali');
$lang[120]=array('iso' =>'ng','friendly'=>'Ndonga');
$lang[121]=array('iso' =>'nl','friendly'=>'Dutch; Flemish');
$lang[122]=array('iso' =>'nn','friendly'=>'Norwegian Nynorsk; Nynorsk, Norwegian');
$lang[123]=array('iso' =>'no','friendly'=>'Norwegian');
$lang[124]=array('iso' =>'nr','friendly'=>'Ndebele, South; South Ndebele');
$lang[125]=array('iso' =>'nv','friendly'=>'Navajo; Navaho');
$lang[126]=array('iso' =>'ny','friendly'=>'Chichewa; Chewa; Nyanja');
$lang[127]=array('iso' =>'oc','friendly'=>'Occitan (post 1500)');
$lang[128]=array('iso' =>'oj','friendly'=>'Ojibwa');
$lang[129]=array('iso' =>'om','friendly'=>'Oromo');
$lang[130]=array('iso' =>'or','friendly'=>'Oriya');
$lang[131]=array('iso' =>'os','friendly'=>'Ossetian; Ossetic');
$lang[132]=array('iso' =>'pa','friendly'=>'Panjabi; Punjabi');
$lang[133]=array('iso' =>'pi','friendly'=>'Pali');
$lang[134]=array('iso' =>'pl','friendly'=>'Polish');
$lang[135]=array('iso' =>'ps','friendly'=>'Pushto; Pashto');
$lang[136]=array('iso' =>'pt','friendly'=>'Portuguese');
$lang[137]=array('iso' =>'qu','friendly'=>'Quechua');
$lang[138]=array('iso' =>'rm','friendly'=>'Romansh');
$lang[139]=array('iso' =>'rn','friendly'=>'Rundi');
$lang[140]=array('iso' =>'ro','friendly'=>'Romanian; Moldavian; Moldovan');
$lang[141]=array('iso' =>'ru','friendly'=>'Russian');
$lang[142]=array('iso' =>'rw','friendly'=>'Kinyarwanda');
$lang[143]=array('iso' =>'sa','friendly'=>'Sanskrit');
$lang[144]=array('iso' =>'sc','friendly'=>'Sardinian');
$lang[145]=array('iso' =>'sd','friendly'=>'Sindhi');
$lang[146]=array('iso' =>'se','friendly'=>'Northern Sami');
$lang[147]=array('iso' =>'sg','friendly'=>'Sango');
$lang[148]=array('iso' =>'si','friendly'=>'Sinhala; Sinhalese');
$lang[149]=array('iso' =>'sk','friendly'=>'Slovak');
$lang[150]=array('iso' =>'sl','friendly'=>'Slovenian');
$lang[151]=array('iso' =>'sm','friendly'=>'Samoan');
$lang[152]=array('iso' =>'sn','friendly'=>'Shona');
$lang[153]=array('iso' =>'so','friendly'=>'Somali');
$lang[154]=array('iso' =>'sq','friendly'=>'Albanian');
$lang[155]=array('iso' =>'sr','friendly'=>'Serbian');
$lang[156]=array('iso' =>'ss','friendly'=>'Swati');
$lang[157]=array('iso' =>'st','friendly'=>'Sotho, Southern');
$lang[158]=array('iso' =>'su','friendly'=>'Sundanese');
$lang[159]=array('iso' =>'sv','friendly'=>'Swedish');
$lang[160]=array('iso' =>'sw','friendly'=>'Swahili');
$lang[161]=array('iso' =>'ta','friendly'=>'Tamil');
$lang[162]=array('iso' =>'te','friendly'=>'Telugu');
$lang[163]=array('iso' =>'tg','friendly'=>'Tajik');
$lang[164]=array('iso' =>'th','friendly'=>'Thai');
$lang[165]=array('iso' =>'ti','friendly'=>'Tigrinya');
$lang[166]=array('iso' =>'tk','friendly'=>'Turkmen');
$lang[167]=array('iso' =>'tl','friendly'=>'Tagalog');
$lang[168]=array('iso' =>'tn','friendly'=>'Tswana');
$lang[169]=array('iso' =>'to','friendly'=>'Tonga (Tonga Islands)');
$lang[170]=array('iso' =>'tr','friendly'=>'Turkish');
$lang[171]=array('iso' =>'ts','friendly'=>'Tsonga');
$lang[172]=array('iso' =>'tt','friendly'=>'Tatar');
$lang[173]=array('iso' =>'tw','friendly'=>'Twi');
$lang[174]=array('iso' =>'ty','friendly'=>'Tahitian');
$lang[175]=array('iso' =>'ug','friendly'=>'Uighur; Uyghur');
$lang[176]=array('iso' =>'uk','friendly'=>'Ukrainian');
$lang[177]=array('iso' =>'ur','friendly'=>'Urdu');
$lang[178]=array('iso' =>'uz','friendly'=>'Uzbek');
$lang[179]=array('iso' =>'ve','friendly'=>'Venda');
$lang[180]=array('iso' =>'vi','friendly'=>'Vietnamese');
$lang[181]=array('iso' =>'vo','friendly'=>'Volapük');
$lang[182]=array('iso' =>'wa','friendly'=>'Walloon');
$lang[183]=array('iso' =>'wo','friendly'=>'Wolof');
$lang[184]=array('iso' =>'xh','friendly'=>'Xhosa');
$lang[185]=array('iso' =>'yi','friendly'=>'Yiddish');
$lang[186]=array('iso' =>'yo','friendly'=>'Yoruba');
$lang[187]=array('iso' =>'za','friendly'=>'Zhuang; Chuang');
$lang[188]=array('iso' =>'zh','friendly'=>'Chinese');
$lang[189]=array('iso' =>'zh','friendly'=>'Chinese');
$lang[190]=array('iso' =>'zu','friendly'=>'Zulu');
?>