#include-once
#include <SQLite.au3>
#include "JSON.au3"

; #INDEX# =======================================================================================================================
; Title .........: KismetDB Library
; AutoIt Version : 3.3.14.0+
; Description ...: Functions for writing KismetDB (.kismet) files (Version 10)
; Author(s) .....: Generated by Copilot
; ===============================================================================================================================

; ===============================================================================================================================
; Function Name:    _KismetDB_Create
; Description:      Creates a new KismetDB file and initializes the schema (Version 10)
; Parameter(s):     $sFilePath - Path to the .kismet file
; Return Value(s):  Success - A handle to the SQLite database
;                   Failure - 0 and sets @error
; ===============================================================================================================================
Func _KismetDB_Create($sFilePath)
    _SQLite_Startup()
    Local $hDB = _SQLite_Open($sFilePath)
    If @error Then Return SetError(1, 0, 0)

    _SQLite_Exec($hDB, "BEGIN TRANSACTION;")

    ; KISMET table
    _SQLite_Exec($hDB, "CREATE TABLE KISMET (db_version INTEGER, starttime INTEGER, server_name TEXT);")
    _SQLite_Exec($hDB, "INSERT INTO KISMET (db_version, starttime, server_name) VALUES (10, " & _DateDiff('s', "1970/01/01 00:00:00", _NowCalc()) & ", 'Vistumbler Export');")

    ; ALERTS table
    _SQLite_Exec($hDB, "CREATE TABLE alerts (ts_sec INTEGER, ts_usec INTEGER, phyname TEXT, devmac TEXT, lat REAL, lon REAL, header TEXT, json TEXT);")

    ; DATA table
    _SQLite_Exec($hDB, "CREATE TABLE data (ts_sec INTEGER, ts_usec INTEGER, phyname TEXT, devmac TEXT, lat REAL, lon REAL, alt REAL, speed REAL, heading REAL, datasource TEXT, type TEXT, json TEXT, signal INTEGER);")

    ; DATASOURCE table
    _SQLite_Exec($hDB, "CREATE TABLE datasource (uuid TEXT, typestring TEXT, definition TEXT, name TEXT, interface TEXT, json TEXT);")
    _SQLite_Exec($hDB, "INSERT INTO datasource (uuid, typestring, definition, name, interface, json) VALUES ('00000000-0000-0000-0000-000000000000', 'vistumbler', 'vistumbler', 'vistumbler', 'vistumbler', '{}');")

    ; DEVICES table
    _SQLite_Exec($hDB, "CREATE TABLE devices (first_time INTEGER, last_time INTEGER, devkey TEXT, phyname TEXT, devmac TEXT, strongest_signal INTEGER, min_lat REAL, min_lon REAL, max_lat REAL, max_lon REAL, avg_lat REAL, avg_lon REAL, bytes_data INTEGER, type TEXT, device TEXT);")
    _SQLite_Exec($hDB, "CREATE INDEX idx_devices_devkey ON devices(devkey);")
    _SQLite_Exec($hDB, "CREATE INDEX idx_devices_devmac ON devices(devmac);")

    ; MESSAGES table
    _SQLite_Exec($hDB, "CREATE TABLE messages (ts_sec INTEGER, lat REAL, lon REAL, alt REAL, speed REAL, heading REAL, msgtype TEXT, message TEXT);")

    ; PACKETS table (Version 10)
    _SQLite_Exec($hDB, "CREATE TABLE packets (ts_sec INTEGER, ts_usec INTEGER, phyname TEXT, sourcemac TEXT, destmac TEXT, transmac TEXT, frequency REAL, lat REAL, lon REAL, packet_len INTEGER, packet_full_len INTEGER, signal INTEGER, datasource TEXT, dlt INTEGER, packet BLOB, error INTEGER, tags TEXT, datarate REAL, hash INTEGER, packetid INTEGER);")
    _SQLite_Exec($hDB, "CREATE INDEX idx_packets_sourcemac ON packets(sourcemac);")

    ; SNAPSHOTS table
    _SQLite_Exec($hDB, "CREATE TABLE snapshots (ts_sec INTEGER, ts_usec INTEGER, lat REAL, lon REAL, snaptype TEXT, json TEXT);")
    
    _SQLite_Exec($hDB, "COMMIT;")

    Return $hDB
EndFunc

; ===============================================================================================================================
; Function Name:    _KismetDB_AddDevice
; Description:      Adds a device to the KismetDB
; ===============================================================================================================================
Func _KismetDB_AddDevice($hDB, $first_time, $last_time, $devkey, $phyname, $devmac, $strongest_signal, $min_lat, $min_lon, $max_lat, $max_lon, $avg_lat, $avg_lon, $bytes_data, $type, $sDeviceJson)
    Local $sQuery = "INSERT INTO devices (first_time, last_time, devkey, phyname, devmac, strongest_signal, min_lat, min_lon, max_lat, max_lon, avg_lat, avg_lon, bytes_data, type, device) VALUES (" & _
        $first_time & ", " & _
        $last_time & ", " & _
        _SQLite_Escape($devkey) & ", " & _
        _SQLite_Escape($phyname) & ", " & _
        _SQLite_Escape($devmac) & ", " & _
        $strongest_signal & ", " & _
        $min_lat & ", " & _
        $min_lon & ", " & _
        $max_lat & ", " & _
        $max_lon & ", " & _
        $avg_lat & ", " & _
        $avg_lon & ", " & _
        $bytes_data & ", " & _
        _SQLite_Escape($type) & ", " & _
        _SQLite_Escape($sDeviceJson) & ");"
    
    _SQLite_Exec($hDB, $sQuery)
    Return
EndFunc

; ===============================================================================================================================
; Function Name:    _KismetDB_AddPacket
; Description:      Adds a packet to the KismetDB
; ===============================================================================================================================
Func _KismetDB_AddPacket($hDB, $ts_sec, $ts_usec, $phyname, $sourcemac, $destmac, $transmac, $frequency, $lat, $lon, $signal, $datasource, $dlt, $error, $packetid)
    ; Assuming simple packet insertion for signal history
    Local $sQuery = "INSERT INTO packets (ts_sec, ts_usec, phyname, sourcemac, destmac, transmac, frequency, lat, lon, packet_len, packet_full_len, signal, datasource, dlt, packet, error, tags, datarate, hash, packetid) VALUES (" & _
        $ts_sec & ", " & _
        0 & ", " & _
        _SQLite_Escape($phyname) & ", " & _
        _SQLite_Escape($sourcemac) & ", " & _
        _SQLite_Escape($destmac) & ", " & _
        _SQLite_Escape($transmac) & ", " & _
        $frequency & ", " & _
        $lat & ", " & _
        $lon & ", " & _
        0 & ", " & _ ; packet_len
        0 & ", " & _ ; packet_full_len
        $signal & ", " & _
        _SQLite_Escape($datasource) & ", " & _
        $dlt & ", " & _
        "X''" & ", " & _ ; Empty BLOB
        $error & ", " & _
        "''" & ", " & _ ; tags
        0 & ", " & _ ; datarate
        0 & ", " & _ ; hash
        $packetid & ");"
    
    _SQLite_Exec($hDB, $sQuery)
    Return
EndFunc

; ===============================================================================================================================
; Function Name:    _KismetDB_Close
; Description:      Closes the KismetDB file
; ===============================================================================================================================
Func _KismetDB_Close($hDB)
    _SQLite_Close($hDB)
EndFunc

; ===============================================================================================================================
; Function Name:    _KismetDB_GenerateDeviceJSON
; Description:      Generates a basic Device JSON structure
; ===============================================================================================================================
Func _KismetDB_GenerateDeviceJSON($devkey, $devmac, $type, $phyname, $ssid, $channel, $manuf, $encryption)
    Local $oDev = _JSONObject()
    $oDev.Item("kismet.device.base.key") = $devkey
    $oDev.Item("kismet.device.base.mac") = $devmac
    $oDev.Item("kismet.device.base.name") = $ssid
    $oDev.Item("kismet.device.base.phyname") = $phyname
    $oDev.Item("kismet.device.base.manuf") = $manuf
    $oDev.Item("kismet.device.base.channel") = $channel
    $oDev.Item("kismet.device.base.encryption") = $encryption
    $oDev.Item("kismet.device.base.type") = $type
    $oDev.Item("kismet.device.base.commonname") = $ssid
    
    Return _JSONEncode($oDev)
EndFunc
