#include-once

; #INDEX# =======================================================================================================================
; Title .........: NetXML Library
; AutoIt Version : 3.3.14.0+
; Description ...: Functions for writing NetXML (.netxml) files
; Author(s) .....: Generated by Copilot
; ===============================================================================================================================

Global $__sNetXML_Content = ""

; ===============================================================================================================================
; Function Name:    _NetXML_Create
; Description:      Initializes the NetXML content
; ===============================================================================================================================
Func _NetXML_Create($sVersion = "0.1")
    $__sNetXML_Content = '<?xml version="1.0" encoding="ISO-8859-1"?>' & @CRLF
    $__sNetXML_Content &= '<!DOCTYPE detection-run SYSTEM "http://kismetwireless.net/kismet-3.1.0.dtd">' & @CRLF
    $__sNetXML_Content &= '<detection-run kismet-version="Vistumbler" start-time="' & _NowCalc() & '">' & @CRLF
    $__sNetXML_Content &= '<card-source uuid="00000000-0000-0000-0000-000000000000">vistumbler</card-source>' & @CRLF
EndFunc

; ===============================================================================================================================
; Function Name:    _NetXML_AddNetwork
; Description:      Adds a wireless-network entry
; ===============================================================================================================================
Func _NetXML_AddNetwork($bssid, $ssid, $manuf, $channel, $freq, $type, $encrypt, $essid_cloaked, $first_time, $last_time, $max_rate, $max_signal, $min_signal, $datasize, $gps_lat, $gps_lon, $gps_alt, $gps_speed)
    Local $sNet = '<wireless-network number="0" type="' & $type & '" first-time="' & $first_time & '" last-time="' & $last_time & '">' & @CRLF
    $sNet &= '  <SSID first-time="' & $first_time & '" last-time="' & $last_time & '">' & @CRLF
    $sNet &= '    <type>' & $type & '</type>' & @CRLF
    $sNet &= '    <max-rate>' & $max_rate & '</max-rate>' & @CRLF
    $sNet &= '    <packets>0</packets>' & @CRLF
    $sNet &= '    <beaconrate>10</beaconrate>' & @CRLF
    $sNet &= '    <encryption>' & $encrypt & '</encryption>' & @CRLF
    $sNet &= '    <essid cloaked="' & $essid_cloaked & '">' & _XMLEncode($ssid) & '</essid>' & @CRLF
    $sNet &= '  </SSID>' & @CRLF
    $sNet &= '  <BSSID>' & $bssid & '</BSSID>' & @CRLF
    $sNet &= '  <manuf>' & _XMLEncode($manuf) & '</manuf>' & @CRLF
    $sNet &= '  <channel>' & $channel & '</channel>' & @CRLF
    $sNet &= '  <freqmhz>' & $freq & ' 0</freqmhz>' & @CRLF
    $sNet &= '  <maxseenrate>' & $max_rate & '</maxseenrate>' & @CRLF
    $sNet &= '  <snr-info>' & @CRLF
    $sNet &= '    <last_signal_dbm>' & $max_signal & '</last_signal_dbm>' & @CRLF
    $sNet &= '    <last_noise_dbm>0</last_noise_dbm>' & @CRLF
    $sNet &= '    <last_signal_rssi>' & $max_signal & '</last_signal_rssi>' & @CRLF
    $sNet &= '    <last_noise_rssi>0</last_noise_rssi>' & @CRLF
    $sNet &= '    <min_signal_dbm>' & $min_signal & '</min_signal_dbm>' & @CRLF
    $sNet &= '    <min_noise_dbm>0</min_noise_dbm>' & @CRLF
    $sNet &= '    <min_signal_rssi>' & $min_signal & '</min_signal_rssi>' & @CRLF
    $sNet &= '    <min_noise_rssi>0</min_noise_rssi>' & @CRLF
    $sNet &= '    <max_signal_dbm>' & $max_signal & '</max_signal_dbm>' & @CRLF
    $sNet &= '    <max_noise_dbm>0</max_noise_dbm>' & @CRLF
    $sNet &= '    <max_signal_rssi>' & $max_signal & '</max_signal_rssi>' & @CRLF
    $sNet &= '    <max_noise_rssi>0</max_noise_rssi>' & @CRLF
    $sNet &= '  </snr-info>' & @CRLF
    
    If $gps_lat <> 0 Or $gps_lon <> 0 Then
        $sNet &= '  <gps-info>' & @CRLF
        $sNet &= '    <min-lat>' & $gps_lat & '</min-lat>' & @CRLF
        $sNet &= '    <min-lon>' & $gps_lon & '</min-lon>' & @CRLF
        $sNet &= '    <min-alt>' & $gps_alt & '</min-alt>' & @CRLF
        $sNet &= '    <min-spd>' & $gps_speed & '</min-spd>' & @CRLF
        $sNet &= '    <max-lat>' & $gps_lat & '</max-lat>' & @CRLF
        $sNet &= '    <max-lon>' & $gps_lon & '</max-lon>' & @CRLF
        $sNet &= '    <max-alt>' & $gps_alt & '</max-alt>' & @CRLF
        $sNet &= '    <max-spd>' & $gps_speed & '</max-spd>' & @CRLF
        $sNet &= '    <peak-lat>' & $gps_lat & '</peak-lat>' & @CRLF
        $sNet &= '    <peak-lon>' & $gps_lon & '</peak-lon>' & @CRLF
        $sNet &= '    <peak-alt>' & $gps_alt & '</peak-alt>' & @CRLF
        $sNet &= '    <peak-spd>' & $gps_speed & '</peak-spd>' & @CRLF
        $sNet &= '    <avg-lat>' & $gps_lat & '</avg-lat>' & @CRLF
        $sNet &= '    <avg-lon>' & $gps_lon & '</avg-lon>' & @CRLF
        $sNet &= '    <avg-alt>' & $gps_alt & '</avg-alt>' & @CRLF
        $sNet &= '    <avg-spd>' & $gps_speed & '</avg-spd>' & @CRLF
        $sNet &= '  </gps-info>' & @CRLF
    EndIf

    $sNet &= '  <datasize>' & $datasize & '</datasize>' & @CRLF
    $sNet &= '</wireless-network>' & @CRLF
    
    $__sNetXML_Content &= $sNet
EndFunc

; ===============================================================================================================================
; Function Name:    _NetXML_Save
; Description:      Saves the NetXML content to a file
; ===============================================================================================================================
Func _NetXML_Save($sFilePath)
    $__sNetXML_Content &= '</detection-run>'
    Local $hFile = FileOpen($sFilePath, 2 + 8) ; Overwrite + Create Dir
    FileWrite($hFile, $__sNetXML_Content)
    FileClose($hFile)
EndFunc

; ===============================================================================================================================
; Function Name:    _XMLEncode
; Description:      Encodes special characters for XML
; ===============================================================================================================================
Func _XMLEncode($sString)
    $sString = StringReplace($sString, "&", "&amp;")
    $sString = StringReplace($sString, "<", "&lt;")
    $sString = StringReplace($sString, ">", "&gt;")
    $sString = StringReplace($sString, '"', "&quot;")
    $sString = StringReplace($sString, "'", "&apos;")
    Return $sString
EndFunc
